// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203085540_RemoveUniqueIndex")]
    partial class RemoveUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Core.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("LitMarket")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lit_market");

                    b.Property<bool>("LitNet")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lit_net");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Core.Entities.AccountActionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("action_date");

                    b.Property<string>("ActionResult")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("action_result");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_type");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("account_action_history", (string)null);
                });

            modelBuilder.Entity("Core.Entities.AccountSettings", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<string>("AddToLibrary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("add_to_library");

                    b.Property<string>("BuyABook")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("buy_a_book");

                    b.Property<int>("ConstantDelay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000)
                        .HasColumnName("constant_delay");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FloatingIncrementalDelay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(500)
                        .HasColumnName("floating_incremental_delay");

                    b.Property<string>("LikeTheBook")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("like_the_book");

                    b.Property<string>("MakeADonationToTheAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("make_donation_to_the_author");

                    b.Property<string>("PostComment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("post_comment");

                    b.Property<string>("ReadBook")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("read_book");

                    b.Property<int>("ReadProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("read_profile");

                    b.Property<string>("SubscribeToTheAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subscribe_to_the_author");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("account_settings", (string)null);
                });

            modelBuilder.Entity("Core.Entities.AccountActionHistory", b =>
                {
                    b.HasOne("Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Core.Entities.AccountSettings", b =>
                {
                    b.HasOne("Core.Entities.Account", null)
                        .WithOne("AccountSettings")
                        .HasForeignKey("Core.Entities.AccountSettings", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Account", b =>
                {
                    b.Navigation("AccountSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
