// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129102027_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Core.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LitMarket")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LitNet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Core.Entities.AccountSettings", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddToLibrary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyABook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConstantDelay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FloatingIncrementalDelay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LikeTheBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MakeADonationToTheAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadProfile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscribeToTheAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountSettings");
                });

            modelBuilder.Entity("Core.Entities.ProfileSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ChanceOfRegression")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MinMaxPauseAfterScrolling")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MinMaxScrollDuration")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MinMaxScrollStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountSettingsId", "ProfileType")
                        .IsUnique();

                    b.ToTable("ProfileSettings");
                });

            modelBuilder.Entity("Core.Entities.AccountSettings", b =>
                {
                    b.HasOne("Core.Entities.Account", "Account")
                        .WithOne("AccountSettings")
                        .HasForeignKey("Core.Entities.AccountSettings", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Core.Entities.ProfileSettings", b =>
                {
                    b.HasOne("Core.Entities.AccountSettings", "AccountSettings")
                        .WithMany("ProfileSettings")
                        .HasForeignKey("AccountSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountSettings");
                });

            modelBuilder.Entity("Core.Entities.Account", b =>
                {
                    b.Navigation("AccountSettings");
                });

            modelBuilder.Entity("Core.Entities.AccountSettings", b =>
                {
                    b.Navigation("ProfileSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
